### ISSUE TITLE
[Question] some problem with stop gradient

### ISSUE THREAD

**Issue by yucthonni** [metaopt/torchopt#221]
### Required prerequisites

- [X] I have read the documentation <https://torchopt.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/metaopt/torchopt/issues) and [Discussions](https://github.com/metaopt/torchopt/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/metaopt/torchopt/discussions/new).

### system information
```python
>>> print(sys.version, sys.platform)
3.8.18 (default, Sep 11 2023, 13:40:15) 
[GCC 11.2.0] linux
>>> print(torchopt.__version__,torch.__version__,functorch.__version__)
0.7.3 2.1.2+cu121 2.1.2+cu121
``` 
### problem description
I'm trying to implement MGRL on PPO with a reward network as the hyperparameter to optimize. I meet a problem that I can run the meta-update process for the first time, but in the second round, even though I use 'torchopt.stopgradient' to stop policy, rewardnet and inner_opt, there still comes the error
```
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
``` 
I wonder if it is caused by there is some gradient I haven't stopped or other problem, 
```python
inner_opt = torchopt.MetaSGD(self.policy.actor, lr=self.lr_actor,moment_requires_grad=True)
meta_opt = torch.optim.Adam(self.rewardnet.parameters(), lr=self.lr_actor)

# Optimize policy for K epochs
for _ in range(self.K_epochs):
    for _ in range(self.inner_per_meta):
        # Evaluating old actions and values
        logprobs, state_values, state_values_g, dist_entropy = self.policy.evaluate(old_states, old_actions)

        # match state_values tensor dimensions with rewards tensor
        state_values = torch.squeeze(state_values)
        state_values_g = torch.squeeze(state_values_g)
        
        # Finding the ratio (pi_theta / pi_theta__old)
        log_ratios=logprobs - old_logprobs.detach()
        ratios = torch.exp(log_ratios)
        
        # Calculate Approx-KL
        approx_kl=((ratios-1)-log_ratios).mean()

        # Finding Surrogate Loss  
        surr1_g=ratios *advantages_g
        surr2_g=torch.clamp(ratios, 1-self.eps_clip, 1+self.eps_clip) * advantages_g

        # final loss of clipped objective PPO
        policy_loss = -torch.min(surr1_g, surr2_g) + 0.5 * self.MseLoss(state_values_g, rewards_g) - 0.01 * dist_entropy
        
        # backpropagation
        inner_opt.step(policy_loss.mean())
        
        if self.writer:
            self.writer.add_scalar("loss", policy_loss.mean(), self.cnt)
            self.writer.add_scalar("approx_kl", approx_kl.mean(), self.cnt)
            self.cnt += 1
            
    
    logprobs, state_values, state_values_g, dist_entropy = self.policy.evaluate(old_states, old_actions)
    
    sv=torch.squeeze(state_values)
    ratios = torch.exp(logprobs - old_logprobs.detach())
    
    surr1 = ratios * advantages
    surr2 = torch.clamp(ratios, 1-self.eps_clip, 1+self.eps_clip) * advantages
    
    outer_loss=-torch.min(surr1, surr2)+0.5*self.MseLoss(state_values, rewards)-0.01*dist_entropy
    
    meta_opt.zero_grad()
    outer_loss.mean().backward()
    meta_opt.step()
    
    torchopt.stop_gradient(self.policy)
    torchopt.stop_gradient(self.rewardnet)
    torchopt.stop_gradient(inner_opt)
```

**Comment by Benjamin-eecs** [comment]
Hi, as for MGRL, please refer to the example: https://github.com/metaopt/torchopt/blob/main/examples/MGRL/mgrl.py and usage of stop_gradient which use mgrl as an example: https://github.com/metaopt/torchopt/blob/a4cfc49f27fd623526db1cb13d823ac7ebc5ab41/tutorials/4_Stop_Gradient.ipynb

A quick fix can be sth like:

```python
inner_opt = torchopt.MetaSGD(self.policy.actor, lr=self.lr_actor,moment_requires_grad=True)
meta_opt = torch.optim.Adam(self.rewardnet.parameters(), lr=self.lr_actor)

# Optimize policy for K epochs
for _ in range(self.K_epochs):
    for _ in range(self.inner_per_meta):
        # Evaluating old actions and values
        logprobs, state_values, state_values_g, dist_entropy = self.policy.evaluate(old_states, old_actions)

        # match state_values tensor dimensions with rewards tensor
        state_values = torch.squeeze(state_values)
        state_values_g = torch.squeeze(state_values_g)
        
        # Finding the ratio (pi_theta / pi_theta__old)
        log_ratios=logprobs - old_logprobs.detach()
        ratios = torch.exp(log_ratios)
        
        # Calculate Approx-KL
        approx_kl=((ratios-1)-log_ratios).mean()

        # Finding Surrogate Loss  
        surr1_g=ratios *advantages_g
        surr2_g=torch.clamp(ratios, 1-self.eps_clip, 1+self.eps_clip) * advantages_g

        # final loss of clipped objective PPO
        policy_loss = -torch.min(surr1_g, surr2_g) + 0.5 * self.MseLoss(state_values_g, rewards_g) - 0.01 * dist_entropy
        
        # backpropagation
        inner_opt.step(policy_loss.mean())
        
        if self.writer:
            self.writer.add_scalar("loss", policy_loss.mean(), self.cnt)
            self.writer.add_scalar("approx_kl", approx_kl.mean(), self.cnt)
            self.cnt += 1
            
    
    logprobs, state_values, state_values_g, dist_entropy = self.policy.evaluate(old_states, old_actions)
    
    sv=torch.squeeze(state_values)
    ratios = torch.exp(logprobs - old_logprobs.detach())
    
    surr1 = ratios * advantages
    surr2 = torch.clamp(ratios, 1-self.eps_clip, 1+self.eps_clip) * advantages
    
    outer_loss=-torch.min(surr1, surr2)+0.5*self.MseLoss(state_values, rewards)-0.01*dist_entropy
    
    meta_opt.zero_grad()
    outer_loss.mean().backward()
    meta_opt.step()
    
    # stop gradient of inner model and inner optimizer is enough
    torchopt.stop_gradient(self.policy) 
    torchopt.stop_gradient(inner_opt)
```

**Comment by yucthonni** [comment]
Thank you very much for your suggestions on my code. 
I fix my code but there is still the error,
```python
File "/tmp/ipykernel_511934/3825234752.py", line 1, in <module>
    agent.update()
  File "/home/tools/RL/tri/PPO_meta.py", line 281, in update
    rewards_g = (rewards_g - rewards_g.mean()) [/](https://file+.vscode-resource.vscode-cdn.net/) \
 (Triggered internally at ../torch/csrc/autograd/python_anomaly_mode.cpp:114.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
``` 
```python
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
```
I wonder if the problem is caused by the reward calculation,
```python
rewards_g = []
discounted_reward = 0
for reward_g, is_terminal, state in zip(reversed(self.buffer.rewards_g), reversed(self.buffer.is_terminals), reversed(self.buffer.states)):
    if is_terminal:
        discounted_reward = 0
    w = self.rewardnet(state)
    r = torch.dot(w, torch.FloatTensor(reward_g).to(device).detach())
    discounted_reward = r + (self.gamma * discounted_reward)
    rewards_g.insert(0, discounted_reward)

# Normalizing the rewards_g
rewards_g = torch.stack(rewards_g).to(device)
rewards_g = (rewards_g - rewards_g.mean()) / \
    (rewards_g.std() + 1e-7).to(device)

# convert list to tensor
old_states = torch.squeeze(torch.stack(
    self.buffer.states)).detach().to(device)
old_actions = torch.squeeze(torch.stack(
    self.buffer.actions, dim=0)).detach().to(device)
old_logprobs = torch.squeeze(torch.stack(
    self.buffer.logprobs, dim=0)).detach().to(device)
old_state_values_g = torch.squeeze(torch.stack(
    self.buffer.state_values, dim=0)).detach().to(device)

# calculate advantages & advantages_g
advantages_g = rewards_g - old_state_values_g
``` 
Meanwhile, I find it works when I calculate loss and backward from outside the model just like the example you posted
https://github.com/metaopt/torchopt/blob/main/examples/MGRL/mgrl.py
```python
for _ in trange(outer_epi):
    for _ in trange(inner_epi):
        inner_loss = agent.update_g()
        inner_opt.step(inner_loss)

    outer_loss = agent.update()

    meta_opt.zero_grad()
    outer_loss.backward()
    meta_opt.step()

    torchopt.stop_gradient(agent.policy)
    torchopt.stop_gradient(inner_opt)
``` 
It indeed backward the gradient to reward model, so maybe I can step from outside the model as an alternative.

**Comment by Benjamin-eecs** [comment]
> Thank you very much for your suggestions on my code. I fix my code but there is still the error,
> 
> ```python
> File "/tmp/ipykernel_511934/3825234752.py", line 1, in <module>
>     agent.update()
>   File "/home/tools/RL/tri/PPO_meta.py", line 281, in update
>     rewards_g = (rewards_g - rewards_g.mean()) [/](https://file+.vscode-resource.vscode-cdn.net/) \
>  (Triggered internally at ../torch/csrc/autograd/python_anomaly_mode.cpp:114.)
>   Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
> ```
> 
> ```python
> RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
> ```
> 
> I wonder if the problem is caused by the reward calculation,
> 
> ```python
> rewards_g = []
> discounted_reward = 0
> for reward_g, is_terminal, state in zip(reversed(self.buffer.rewards_g), reversed(self.buffer.is_terminals), reversed(self.buffer.states)):
>     if is_terminal:
>         discounted_reward = 0
>     w = self.rewardnet(state)
>     r = torch.dot(w, torch.FloatTensor(reward_g).to(device).detach())
>     discounted_reward = r + (self.gamma * discounted_reward)
>     rewards_g.insert(0, discounted_reward)
> 
> # Normalizing the rewards_g
> rewards_g = torch.stack(rewards_g).to(device)
> rewards_g = (rewards_g - rewards_g.mean()) / \
>     (rewards_g.std() + 1e-7).to(device)
> 
> # convert list to tensor
> old_states = torch.squeeze(torch.stack(
>     self.buffer.states)).detach().to(device)
> old_actions = torch.squeeze(torch.stack(
>     self.buffer.actions, dim=0)).detach().to(device)
> old_logprobs = torch.squeeze(torch.stack(
>     self.buffer.logprobs, dim=0)).detach().to(device)
> old_state_values_g = torch.squeeze(torch.stack(
>     self.buffer.state_values, dim=0)).detach().to(device)
> 
> # calculate advantages & advantages_g
> advantages_g = rewards_g - old_state_values_g
> ```
> 
> Meanwhile, I find it works when I calculate loss and backward from outside the model just like the example you posted [`main`/examples/MGRL/mgrl.py](https://github.com/metaopt/torchopt/blob/main/examples/MGRL/mgrl.py?rgh-link-date=2024-05-27T07%3A43%3A44Z)
> 
> ```python
> for _ in trange(outer_epi):
>     for _ in trange(inner_epi):
>         inner_loss = agent.update_g()
>         inner_opt.step(inner_loss)
> 
>     outer_loss = agent.update()
> 
>     meta_opt.zero_grad()
>     outer_loss.backward()
>     meta_opt.step()
> 
>     torchopt.stop_gradient(agent.policy)
>     torchopt.stop_gradient(inner_opt)
> ```
> 
> It indeed backwards the gradient to reward model, so maybe I can step from outside the model as an alternative.

Btw, you can also refer to the implementation of https://github.com/MagiFeeney/Bootstrapped-Meta-Learning/blob/main/algo/mgrl.py for a clean mgrl implementation using torchopt==0.4.3, but it can help you understand mgrl logic better.

**Comment by W-Zhi-Chao** [comment]
Hello, I'm wondering whether you have solved your problem. I'm also trying to tuning the reward weight parameter to optimize the agent!
