### ISSUE TITLE
[BUG] Accelerated optimizer test failed on GPU

### ISSUE THREAD

**Issue by Benjamin-eecs** [metaopt/torchopt#30]
## Describe the bug

CUDA part test failed on GPU machine

## Screenshots

![torchopt_bug_2](https://user-images.githubusercontent.com/32269413/179566619-9b6583d7-3ecb-4e65-9442-7145244b38e9.png)

## System info

![torchopt_bug_1](https://user-images.githubusercontent.com/32269413/179566499-2f78a4c1-f91c-4b1a-b2cf-c4ef2d46d457.png)

```python
import torchopt, numpy, sys
print(torchopt.__version__, numpy.__version__, sys.version, sys.platform)
0.4.1 1.22.3 3.8.13 (default, Mar 28 2022, 11:38:47) 
[GCC 7.5.0] linux
```

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://torchopt.readthedocs.io/) (**required**)

**Comment by XuehaiPan** [comment]
Reproduced with NVIDIA A100 GPU:

![image](https://user-images.githubusercontent.com/16078332/183030473-0dc46d51-d138-49ac-b3b0-c915ae302967.png)
