### ISSUE TITLE
[Question] About `torch.optim.lr_scheduler` support

### ISSUE THREAD

**Issue by hccz95** [metaopt/torchopt#75]
## Questions
It seems that optimizers like torchopt.adam does not support torch.optim.lr_scheduler

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://torchopt.readthedocs.io/) (**required**)

**Comment by XuehaiPan** [comment]
@hccz95 Thanks for reporting this! It's a bug and we will fix it in PR #76. New PyPI wheels will be published soon.
